### ISSUE TITLE
question with the path

### ISSUE THREAD

**Issue by Cr1zyYT** [guanaco0403/Guanaco-Firework-Mania-Mods#11]
**mod Guanaco-Firework-Mania-Mods-main

**Which folder should I put the mod in?

**I have a pirate game

**Comment by guanaco0403** [comment]
Sorry mods dont supports cracked version of the game please buy it right here: https://store.steampowered.com/app/1079260/Fireworks_Mania__An_Explosive_Simulator/
i cant do anything for you soo i will close this issue
